# Generated by Django 3.2.8 on 2022-01-24 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email')),
                ('name', models.CharField(max_length=15)),
                ('date', models.DateField()),
                ('gender', models.CharField(choices=[('여', '여자'), ('남', '남자')], max_length=20)),
                ('address', models.CharField(blank=True, max_length=250, null=True)),
                ('phone_num', models.CharField(max_length=16, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': ('유저',),
                'verbose_name_plural': '유저',
                'db_table': 'accounts',
            },
        ),
    ]
