# Generated by Django 3.2.8 on 2022-01-24 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('남', '남자'), ('여', '여자')], max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_num',
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
