# Generated by Django 3.2.8 on 2022-02-12 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('여', '여자'), ('남', '남자')], max_length=20),
        ),
    ]
