# Generated by Django 3.2.8 on 2022-01-27 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('남', '남자'), ('여', '여자')], max_length=20),
        ),
    ]
