# Generated by Django 3.2.8 on 2022-02-14 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart_product',
            options={'verbose_name': '장바구니', 'verbose_name_plural': '장바구니 목록'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': '주문', 'verbose_name_plural': '주문 목록'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': '제품', 'verbose_name_plural': '제품 목록'},
        ),
        migrations.AlterModelOptions(
            name='product_kind',
            options={'verbose_name': '카테고리', 'verbose_name_plural': '제품 카테고리 '},
        ),
        migrations.AlterField(
            model_name='cart_product',
            name='count',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='product',
            name='field',
            field=models.TextField(default=''),
        ),
    ]
