# Generated by Django 3.2.8 on 2022-02-14 14:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_rename_count_cart_product_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart_product',
            name='price',
        ),
        migrations.AddField(
            model_name='cart_product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cart_product',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
