# Generated by Django 3.2.8 on 2022-02-19 20:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20220214_2359'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='destination',
            field=models.CharField(default=django.utils.timezone.now, max_length=500, verbose_name='주소지'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='count',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='purchase_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
