# Generated by Django 3.2.8 on 2022-02-22 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20220219_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='hitcount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
